# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyApp
	pod 'Alamofire', '~> 5.2'
  pod 'Charts', '~> 3.6'
  
  target 'CurrencyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyAppUITests' do
    # Pods for testing
  end

end
